notifications:
  slack: wsi-t113:SRHSOd3CgFDUwFxqv8SCXuIf
  email: false

sudo: false

language: ruby

services:
 - docker

script:
 - echo 'Build and check docker image'
 - docker build -t r-cnv .
 - docker images | grep -c r-cnv
 - echo 'Verify program(s) from this repo'
 - docker run -t --rm r-cnv R --version
 - docker run -t --rm r-cnv Rscript --version

